version: "3.8"

services:
  web:
    container_name: join-up-backend
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    volumes:
      - .:/src
    ports:
      - "8080:8080"

  mongo:
    image: mongo:6.0.13
    container_name: join-up-mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.2
    container_name: join-up-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGODB_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/
    restart: unless-stopped
    depends_on:
      - mongo

volumes:
  dbdata:
